apiVersion: v1
kind: Service
metadata:
  name: {{ include "factorio.fullname" . }}
  labels:
    {{- include "factorio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.portTcp }}
      targetPort: rcon
      protocol: TCP
      name: rcon
    - port: {{ .Values.service.portUdp }}
      targetPort: game
      protocol: UDP
      name: game
  selector:
    {{- include "factorio.selectorLabels" . | nindent 4 }}
